# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20170622_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogacion',
            name='fin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogacion',
            name='inicio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
